<?php 
    $wording = array(
        'th' => array(
            'menu_index' => 'หน้าแรก',
            'menu_aboutus' => 'เกี่ยวกับเรา',
            'menu_lang_th' => 'ภาษาไทย',
            'menu_lang_en' => 'English',
            'index_header' => 'จุดประการให้แผนการของท่าน',
            'index_makruk1' => 'รุกฆาต',
            'index_makruk2' => '(หมากรุกไทย ออนไลน์)',
            'index_chess1' => 'Checkmate',
            'index_chess2' => '(หมากรุกสากล ออนไลน์)',
            'aboutus_header' => 'เกี่ยวกับเรา',
            'aboutus_detail1' => 'White Night Soft คือกลุ่มนักพัฒนาเกม บนอุปกรณ์มือถือ แท็บเล็ด พีซี และอุปกรณ์อื่น ๆ',
            'aboutus_detail2' => 'เรามุ่งมั่นพัฒนาเกมกระดานให้ครอบคลุมทุกประเภท โดยศึกษาแบบแผน วิธีการ กฏกติกา และอื่น ๆ เพื่อให้ผู้เล่น ได้สัมผัสการแข่งขันที่สมจริงที่สุด',
            'aboutus_detail3' => 'ภายใต้สภาพแวดล้อมเดียวกัน รวมถึงการพัฒนาการประเภทอื่น ๆ เพื่อสร้างความบันเทิงให้กับผู้เล่นต่อไปในอนาคต',
            'makruk_header' => 'เลือกสมรภูมิที่ท่านต้องการ',
            'makruk_example_ss' => 'ภาพตัวอย่างในเกม',
            'makruk_ss1' => 'ต่อสู้กับคู่แข่งขันออนไลน์',
            'makruk_ss2' => 'นับศักดิ์หมากและศักดิ์กระดานแบบสมจริง',
            'makruk_ss3' => 'จัดอันดับสูงสุดของเกม',
            'makruk_ss4' => 'ค้นหาผู้เล่นระดับเดียวกัน หรือใกล้เคียงแบบอัตโนมัติ',
            'makruk_ss5' => 'แข่งขันกับเพื่อนแบบออฟไลน์',
            'makruk_ss6' => 'กลับไปดูการเดินหมากทุกเกมที่เคยเล่น',
            'makruk_howtoplay' => 'วิธีการเล่น',
        ),
        'en' => array(
            'menu_index' => 'Home',
            'menu_aboutus' => 'About us',
            'menu_lang_th' => 'Thai',
            'menu_lang_en' => 'English',
            'index_header' => 'Light up your Strategies',
            'index_makruk1' => 'Makruk',
            'index_makruk2' => '(Thai Chess Online)',
            'index_chess1' => 'Checkmate',
            'index_chess2' => '(Chess Online)',
            'aboutus_header' => 'About us',
            'aboutus_detail1' => 'detail 1',
            'aboutus_detail2' => 'detail 2',
            'aboutus_detail3' => 'detail 3',
            'makruk_header' => 'Select your battlefield.',
            'makruk_example_ss' => 'Screen capture',
            'makruk_ss1' => 'Online play against others.',
            'makruk_ss2' => 'The realistic honor-chess or honor-board system.',
            'makruk_ss3' => 'Ranking shows the best of Thai Chess.',
            'makruk_ss4' => 'Search automatically player\'s level closest to your rank.',
            'makruk_ss5' => 'Offline play with your friend.',
            'makruk_ss6' => 'Review your play back all the matches.',
            'makruk_howtoplay' => 'How to play',
        ),
    );
?>


